Missing access/genam.h
Without this, we would start seeing errors like this when compiling:

src/backend/replication/logical/sequencesync.c: In function ‘LogicalRepSyncSequences’:
src/backend/replication/logical/sequencesync.c:607:9: error: unknown type name ‘SysScanDesc’